services:
  - type: web
    name: character-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
